let idioma = document.querySelector("#translate");
const img = document.createElement('img');
const image = document.createElement('img');
img.src = '../img/spain.png';
image.src = '../img/united-kingdom.png';
    traducir(localStorage);
    function traducir(idiomaStorage, input) {
        if(idiomaStorage){
            if (idiomaStorage.idioma == "en") {
                localStorage.setItem("idioma", "en")
                // menu
                document.querySelector("#link1").innerHTML = "Psychologists";
                document.querySelector("#link2").innerHTML = "Frequent questions";
                document.querySelector("#link3").innerHTML = "Testimonials";
                document.querySelector("#link4").innerHTML = "About us";
                if (document.querySelector("#Logout")) {
                    document.querySelector("#Logout").innerHTML = "Logout";
                }
                  if (document.querySelector("#Salir")) {
                    document.querySelector("#Salir").innerHTML = "Log In";
                }
                /*Parte de document querySelector en ingles*/
                document.querySelector("#first-quote").innerHTML = "The losses generated by mood disorders have an impact on the productivity of a country.";
                document.querySelector("#second-quote").innerHTML = "The losses generated by these disorders are not only important in social terms, because mental illnesses also have an enormous impact on the productivity of a country.";
                document.querySelector("#problema1").innerHTML = "Depression";
                document.querySelector("#testi1").innerHTML = "Testimony of Nicole, freshman";
                document.querySelector("#context3").innerHTML = "I suffered from depression from the age of 13 to 16, it is something horrible, your whole world is upset every part of your life and how you function in society is affected";
                document.querySelector(".context2").innerHTML = "The solution was to seek psychological help, take refuge in my family, practice sports, read and play activities, I began to meet and interact with more people because you lock yourself up and the abyss becomes much larger,he explains. Nicole is not the only one who rely on professional assistance to cope with depression.";
                document.querySelector(".context4").innerHTML = "The other thing is to explain well to family members, they help a lot, without their participation it is fatal";
                document.querySelector(".context5").innerHTML = "It is that as Carlos, a second year of high school, who has suffered two episodes of severe depression, has had to drop out of the study. And maybe I'll lose the year.";
                document.querySelector(".context6").innerHTML = "Depression is something that makes us see the world in a very negative way. All the things we do, we do with a very vague feeling that makes us tend to give up the enjoyments of life, says Diego, a former ninth-grade student";
                document.querySelector(".context7").innerHTML = "They all have symptoms in common.";
                document.querySelector(".li1").innerHTML = "Feelings of sadness, which may include crying spells for no apparent reason";
                document.querySelector(".li2").innerHTML = "Frustration or feelings of anger, even over minor matters. (such as failing in a school project).";
                document.querySelector(".li3").innerHTML = "Feelings of hopelessness or emptiness.";
                document.querySelector(".li4").innerHTML = "Loss of interest or pleasure in daily activities.";
                document.querySelector(".leer1").innerHTML = "Read more";
                document.querySelector(".subtitle_1").innerHTML = "Every day there are more who suffer from anxiety disorders, between 15 and 20% of young people in the country have to deal with this type of disorder. But although it is a topic that is being talked about more and more, it is still not enough. Many are the people who suffer from this and do not seek help for fear of being treated as crazy. If you who are reading us are going through this, do not worry, there are people who can help you.";
                document.querySelector(".context8").innerHTML = "The testimonies of 7 girls who suffer from anxiety. If you are in the same situation we want to help you open up and if you have someone in your environment who suffers from it, help them in everything you can. Take a look at these testimonials and you will see that you are not alone and that seeking help really works.";
                document.querySelector(".lipro1").innerHTML = "1. School can be a scary place.";
                document.querySelector(".pro1").innerHTML = "I suffer from anxiety. From the beginning I've had this problem of not talking to people until I feel comfortable enough with them, and this makes everyone think I'm a self-centered jerk. Sometimes I just try to talk to people and end up making things horribly awkward. School is a scary place because the teachers think I'm shy, and they keep forcing me to speak in front of all my classmates, and that's when I start acting weird and making things even worse. Sara, 16 years old, a first-year high school student."
                document.querySelector(".lipro2").innerHTML = "2. And hanging out with very stressful friends.";
                document.querySelector(".pro2").innerHTML = "The thing about social anxiety is that it's a vicious cycle. You want to make friends and socialize, but the stress and fear of being boring or simply having to have a conversation with someone you don't know makes you feel blocked. But missing out and looking at photos and Snapchats from the event the other day only adds to the anxiety, because then you worry about missing out on developing relationships, so the next hangout will be even weirder and more awkward. You want to propose to see them or go to social events, but you are afraid to intervene and be ignored or rejected. And they end up marginalizing you and always leaving you aside because they think that 'you never sign up for anything'. And you feel that people don't really like you and the anxiety ends up winning. Gabriela, 18 years old, third-year high school student.";
                document.querySelector(".lipro3").innerHTML = "3. Being alone doesn't help either.";
                document.querySelector(".pro3").innerHTML = "When I started to develop anxiety, I felt excessively self-conscious in public spaces. Thoughts would start running through my head and I would get disoriented if I couldn't calm down. Soon I began to experience panic attacks on a daily basis. My anxiety made me afraid to be with others and sometimes even to be alone, because being alone meant being alone with my thoughts. As I got older, with the help of a therapist, I learned to deal with it. I still have bad days, but now I know how to live with it!” Adriana, 14 years old, ninth grade student";
                document.querySelector(".lipro4").innerHTML = "4. And that you miss the best moments of life.";
                document.querySelector(".pro4").innerHTML = "My battle with anxiety affects every aspect of my life and everything I do. I get extremely nervous and uncomfortable around new and old people, constantly finding myself not knowing how to open up to others or even wanting to. Anxiety continually keeps me from participating in activities like school clubs or events, hanging out with friends, spending time with my family, or even going to my Zumba class. Having anxiety keeps me from so many wonderful moments in life that I would love to just live. Angie, 17 years old, a sophomore in high school.";
                document.querySelector(".lipro5").innerHTML = "5. There should be no prejudice.";
                document.querySelector(".pro5").innerHTML = "My mother suffers from bipolar disorder, anxiety, depression and alcoholism. When I started Third Cycle I started having panic and anxiety attacks, especially after the elections. Because I was familiar with mental illness, I was able to realize that the anxiety I was suffering from was not terrible and I received the help I needed. I want people to understand that there should be no prejudice for suffering from mental illnesses, so these illnesses could be addressed and treated.” Emiliana, 15 years old, a first-year high school student.";
                document.querySelector(".lipro6").innerHTML = "6. Therapy and medication can help a lot.";
                document.querySelector(".pro6").innerHTML = "I developed an anxiety disorder when I was 14 years old. I started having anxiety attacks when I was studying for math tests. I was doing therapy on and off for two years, and recently started taking anxiety medication which has been helping me quite a bit. I was afraid to take medication because I didn't want to be labeled as crazy or people judge me for it. But who cares! My fight is not over yet, but I am much better.” Karla, 15 years old, first year high school student";
                document.querySelector(".lipro7").innerHTML = "7. You may need to make changes in your life to recover";
                document.querySelector(".pro7").innerHTML = "Due to my bipolar disorder which led to anxiety, and I have to live a very structured life. I take my medication in the morning with breakfast and I can't skip a day, I hardly drink, and I need 8-10 hours of sleep each night. I used to think that it made me a boring person compared to my previous lifestyle, characterized by great impulsiveness, partying, lack of responsibility with my studies. But looking back I am significantly healthier and happier because of the changes I have made. My friends and family have been great to me regarding my condition, offering me unconditional love and support and I feel extremely lucky for that. What has also helped me a lot in dealing with my illness, along with medication and therapy, is regular exercise; I practice yoga daily and walk everywhere, which has reduced my anxiety in general and has weakened the effects of my bipolarity.” Veronica, 18 years old, third-year high school student.";
                document.querySelector(".leer50").innerHTML = "Read More...";
                document.querySelector(".sub2").innerHTML = "Teens, just like adults, can experience stress every day and can benefit from learning stress management skills. Most teens experience more stress when they perceive a situation as dangerous, difficult, or painful and they don't have the resources to deal with it. Some of the sources of stress for teens can include:.";
                document.querySelector(".deri1").innerHTML = "The demands and frustrations of school";
                document.querySelector(".deri2").innerHTML = "Negative thoughts and feelings about themselves";
                document.querySelector(".deri3").innerHTML = "The changes in their bodies";
                document.querySelector(".deri4").innerHTML = "Problems with their friends and/or peers at school";
                document.querySelector(".deri5").innerHTML = "The separation or divorce of your parents";
                document.querySelector(".leer2").innerHTML = "Problems with their friends and/or peers at school";
                document.querySelector(".context10").innerHTML = "Personal development";
                document.querySelector(".context11").innerHTML = "My problems started when I was transferred to a so-called big club. I had always dreamed of getting there as a fanatical fan since my childhood. And who wouldn't want to play for a big top club?";
                document.querySelector(".context12").innerHTML = "But I felt pressure. Something that had never affected me in my home club. In training I brought out the best in me and for the coach I was the starter nailed for the position. But he could not perform in the games, and he declined even more, in those considered key. In short, what the fans call: His shirt is heavy.";
                document.querySelector(".context13").innerHTML = "On the pitch, he dazzled me. In each of my appearances, I felt the eyes of thousands of fans on the back of my neck evaluating me, as if I were going to take a momentous penalty for a defining final match. In the responsibility of solving each play masterfully, as my fame preceded, it made me doubt and I did not enjoy the game itself. Until playing became an ordeal and took away my rest and sleep. I reached the bottom of the well when I suffered a silly, avoidable injury, which I admit I looked for. I thought I was going to leave the boots forever.";
                document.querySelector(".context14").innerHTML = "I worked with the principles of metaphysics for some time, and today I am loved by the fans and the coaching staff. I pay and give satisfaction both to them and to me. And fundamentally, I BELIEVE IN ME. The pressure ceased to weigh on my conscience. I fully trust and enjoy myself, and I love what I do, which is to play in the club of my loves.";
                document.querySelector(".context15").innerHTML = "Problems with their friends and/or peers at school";
                document.querySelector(".context16").innerHTML = "Childhood, he describes as lost in his own thoughts or in the clouds. A quiet, introverted and shy girl. At school learning was difficult for him. It was frustrating not to be applied like her friends, also her motor skills generated a lot of frustration for not being able to play spring, airplane, burns, bolley, basketball, just like her friends from school. She isolated herself because she didn't fit in with groups of friends. This affected their self-esteem and self-concept. She was often humiliated by her classmates and/or teachers for her learning difficulties";
                document.querySelector(".context17").innerHTML = "What to say in adolescence: mathematics, physics and chemistry barely passed the exams. It was hard for him to make decisions, to concentrate. I wanted to study a career that had no numbers.";
                document.querySelector(".context18").innerHTML = "In his first years in high school, he struggled to understand the instructions, to do the best possible job.";
                document.querySelector(".context19").innerHTML = "Lack of attention"
                document.querySelector(".more1").innerHTML = "Read More About...";
                document.querySelector(".more2").innerHTML = "What is stress?";
                document.querySelector(".leer50").innerHTML = "Read More";
                document.querySelector(".leer4").innerHTML = "Read More";
                document.querySelector(".leer5").innerHTML = "Read More";
                document.querySelector(".more2").innerHTML = "What is stress?";
                document.querySelector(".more3").innerHTML = "What is anxiety?";
                document.querySelector(".more4").innerHTML = "What is depression?";
                document.querySelector(".more5").innerHTML = "What is ADHD?";
                document.querySelector(".more6").innerHTML = "What Personal development?";
              /*Parte de document querySelector en ingles*/
                   // footer
                document.querySelector("#fo1").innerHTML = "Home" 
                document.querySelector("#fo2").innerHTML = "About us"
                document.querySelector("#fo3").innerHTML = "Psychologists"
                document.querySelector("#fo4").innerHTML = "Help centers";
                document.querySelector(".social-text").innerHTML = "Our social networks!"
                // checkedbutton
                document.querySelector(".trans").appendChild(img).style.width = "50px";
                document.querySelector(".trans").appendChild(image).style.width = "50px";
                document.querySelector(".trans").removeChild(image);
            }
            else{
                localStorage.setItem("idioma", "es")
                document.querySelector("#link1").innerHTML = "Psicólogos";
                document.querySelector("#link2").innerHTML = "Preguntas frecuentes";
                document.querySelector("#link3").innerHTML = "Testimonios";
                document.querySelector("#link4").innerHTML = "Nuestra identidad";
                if (document.querySelector("#Logout")) {
                    document.querySelector("#Logout").innerHTML = "Salir";
                }
                  if (document.querySelector("#Salir")) {
                    document.querySelector("#Salir").innerHTML = "Entrar";
                }
                   /*Parte de document querySelector en Español*/
                   document.querySelector("#first-quote").innerHTML = "Las pérdidas generadas por los trastornos del estado de ánimo repercuten en la productividad de un país.";
                   document.querySelector("#second-quote").innerHTML = "Las pérdidas que generan estos trastornos no solo son importantes en términos sociales, pues las enfermedades mentales también tienen un enorme impacto en la productividad de un país.";
                   document.querySelector("#problema1").innerHTML = "Depresión";
                   document.querySelector("#testi1").innerHTML = "Testimonio de Nicole, estudiante de primer año";
                   document.querySelector("#context3").innerHTML = "Sufrí de depresión desde los 13 a los 16 años, es algo horrible, todo tu mundo está trastornado cada parte de tu vida y cómo te desenvuelves en la sociedad se ve afectada";
                   document.querySelector(".context2").innerHTML = "La solución fue buscar ayuda psicológica, refugiarme en mi familia, practicar deportes, leer y jugar actividades, comencé a conocer e interactuar con más personas porque uno se encierra y el abismo se hace mucho más grande, explica. Nicole no es la única que confía en la asistencia profesional para hacer frente a la depresión.";
                   document.querySelector(".context4").innerHTML = "Lo otro es explicar bien a los familiares, ayudan mucho, sin su participación es fatal";
                   document.querySelector(".context5").innerHTML = "Es que como Carlos, estudiante de segundo de bachillerato, que ha sufrido dos episodios de depresión severa, ha tenido que abandonar el estudio. Y a lo mejor me pierdo el año.";
                   document.querySelector(".context6").innerHTML = "La depresión es algo que nos hace ver el mundo de una manera muy negativa. Todas las cosas que hacemos, las hacemos con un sentimiento muy vago que nos hace tender a renunciar a los placeres de la vida, dice Diego, exalumno de noveno grado.";
                   document.querySelector(".context7").innerHTML = "Todos ellos tienen síntomas en común.";
                   document.querySelector(".li1").innerHTML = "Sentimientos de tristeza, que pueden incluir accesos de llanto sin razón aparente";
                   document.querySelector(".li2").innerHTML = "Frustración o sentimientos de ira, incluso por asuntos menores. (como fracasar en un proyecto escolar).";
                   document.querySelector(".li3").innerHTML = "Sentimientos de desesperanza o vacío.";
                   document.querySelector(".li4").innerHTML = "Pérdida de interés o placer en las actividades diarias.";
                   document.querySelector(".leer1").innerHTML = "Leer más";
                   document.querySelector(".subtitle_1").innerHTML = "Cada día son más los que padecen trastornos de ansiedad, entre el 15 y el 20% de los jóvenes del país tienen que lidiar con este tipo de trastorno. Pero aunque es un tema del que se habla cada vez más, todavía no es suficiente. Muchas son las personas que sufren de esto y no buscan ayuda por miedo a ser tratados como locos. Si tú que nos estás leyendo estás pasando por esto, no te preocupes, hay personas que te pueden ayudar.";
                   document.querySelector(".context8").innerHTML = "Los testimonios de 7 niñas que sufren de ansiedad. Si estás en la misma situación queremos ayudarte a que te abras y si tienes a alguien de tu entorno que lo padezca, ayúdalo en todo lo que puedas. Echa un vistazo a estos testimonios y verás que no estás solo y que buscar ayuda realmente funciona.";
                   document.querySelector(".lipro1").innerHTML = "1. La escuela puede ser un lugar aterrador.";
                   document.querySelector(".pro1").innerHTML = "Sufro de ansiedad. Desde el principio he tenido este problema de no hablar con la gente hasta que me siento lo suficientemente cómodo con ellos, y esto hace que todos piensen que soy un idiota egocéntrico. A veces solo trato de hablar con la gente y termino haciendo las cosas terriblemente incómodas. La escuela es un lugar aterrador porque los maestros suponen que soy tímido y me siguen obligando a hablar frente a todos mis compañeros de clase, y ahí es cuando empiezo a actuar raro y empeorar las cosas. Sara, 16 años, estudiante de primer año de secundaria."
                   document.querySelector(".lipro2").innerHTML = "2. Y salir con amigas muy estresantes.";
                   document.querySelector(".pro2").innerHTML = "Lo que pasa con la ansiedad social es que es un círculo vicioso. Quieres hacer amigos y socializar, pero el estrés y el miedo a ser aburrido o simplemente tener que tener una conversación con alguien que no conoces te hace sentir bloqueado. Pero perderse y mirar fotos y snapchats del evento del otro día solo aumenta la ansiedad, porque entonces te preocupas por perderte el desarrollo de relaciones, por lo que el próximo lugar de reunión será aún más extraño e incómodo. Quiere proponer, verlos o ir a eventos sociales, pero tiene miedo de intervenir y ser ignorado o rechazado. Y acaban marginándote y dejándote siempre de lado porque piensan que 'nunca te apuntas a nada'. Y sientes que no le caes bien a la gente y te acaba ganando la ansiedad. Gabriela, 18 años, estudiante de tercer año de secundaria.";
                   document.querySelector(".lipro3").innerHTML = "3. Estar solo tampoco ayuda.";
                   document.querySelector(".pro3").innerHTML = "”Cuando comencé a desarrollar ansiedad, me sentía excesivamente cohibido en los espacios públicos. Los pensamientos comenzaban a correr por mi cabeza y me desorientaba si no podía calmarme. Pronto comencé a experimentar ataques de pánico a diario. Mi ansiedad me hizo tener miedo de estar con los demás y, a veces, incluso de estar solo, porque estar solo significaba estar solo con mis pensamientos. A medida que fui creciendo, con la ayuda de un terapeuta, aprendí a lidiar con eso. Todavía tengo días malos, ¡pero ahora sé cómo vivir con eso!”. Adriana, 14 años, estudiante de noveno grado";
                   document.querySelector(".lipro4").innerHTML = "4. Y que te pierdas los mejores momentos de la vida.";
                   document.querySelector(".pro4").innerHTML = "Mi batalla contra la ansiedad afecta todos los aspectos de mi vida y todo lo que hago. Me pongo extremadamente nervioso e incómodo con personas nuevas y viejas, y constantemente me doy cuenta de que no sé cómo abrirme a los demás o ni siquiera quiero hacerlo. La ansiedad continuamente me impide participar en actividades como clubes o eventos escolares, salir con amigos, pasar tiempo con mi familia o incluso ir a mi clase de Zumba. Tener ansiedad me impide vivir tantos momentos maravillosos en la vida que me encantaría vivir. Angie, 17 años, estudiante de segundo año de secundaria.";
                   document.querySelector(".lipro5").innerHTML = "5. No debe haber prejuicios.";
                   document.querySelector(".pro5").innerHTML = "Mi madre sufre de trastorno bipolar, ansiedad, depresión y alcoholismo. Cuando comencé Tercer Ciclo comencé a tener ataques de pánico y ansiedad, sobre todo después de las elecciones. Debido a que estaba familiarizado con la enfermedad mental, pude darme cuenta de que la ansiedad que sufría no era terrible y recibí la ayuda que necesitaba. Quiero que la gente entienda que no debe haber prejuicios por sufrir enfermedades mentales, para que estas enfermedades puedan ser abordadas y tratadas”. Emiliana, 15 años, estudiante de primer año de secundaria.";
                   document.querySelector(".lipro6").innerHTML = "6. La terapia y la medicación pueden ayudar mucho.";
                   document.querySelector(".pro6").innerHTML = "Desarrollé un trastorno de ansiedad cuando tenía 14 años. Empecé a tener ataques de ansiedad cuando estaba estudiando para los exámenes de matemáticas. Estuve haciendo terapia intermitentemente durante dos años, y recientemente comencé a tomar medicamentos para la ansiedad que me han ayudado bastante. Tenía miedo de tomar medicamentos porque no quería que me etiquetaran como loco o que la gente me juzgara por ello. ¡Pero a quién le importa! Mi lucha aún no ha terminado, pero estoy mucho mejor”. Karla, 15 años, estudiante de primer año de secundaria";
                   document.querySelector(".lipro7").innerHTML = "7. Es posible que necesite hacer cambios en su vida para recuperarse";
                   document.querySelector(".pro7").innerHTML = "Debido a mi trastorno bipolar que me llevó a la ansiedad, tengo que vivir una vida muy estructurada. Tomo mi medicamento por la mañana con el desayuno y no puedo saltarme un día, casi no bebo y necesito dormir de 8 a 10 horas cada noche. Solía ​pensar que me convertía en una persona aburrida en comparación con mi estilo de vida anterior, caracterizado por una gran impulsividad, fiesta, falta de responsabilidad con mis estudios. Pero mirando hacia atrás, soy significativamente más saludable y feliz debido a los cambios que he realizado. Mis amigos y mi familia han sido muy buenos conmigo con respecto a mi condición, ofreciéndome amor y apoyo incondicionales y me siento muy afortunada por eso. Lo que también me ha ayudado mucho en el manejo de mi enfermedad, junto con la medicación y la terapia, es el ejercicio regular; practico yoga a diario y camino a todos lados, lo que ha reducido mi ansiedad en general y ha debilitado los efectos de mi bipolaridad”. Verónica, 18 años, estudiante de tercer año de secundaria.";
                   document.querySelector(".leer2").innerHTML = "Leer más...";
                   document.querySelector(".sub2").innerHTML = "Los adolescentes, al igual que los adultos, pueden experimentar estrés todos los días y pueden beneficiarse al aprender habilidades para manejar el estrés. La mayoría de los adolescentes experimentan más estrés cuando perciben una situación como peligrosa, difícil o dolorosa y no tienen los recursos para enfrentarla. Algunas de las fuentes de estrés para los adolescentes pueden incluir:";
                   document.querySelector(".deri1").innerHTML = "Las exigencias y frustraciones de la escuela.";
                   document.querySelector(".deri2").innerHTML = "Pensamientos y sentimientos negativos sobre sí mismos.";
                   document.querySelector(".deri3").innerHTML = "Los cambios en sus cuerpos.";
                   document.querySelector(".deri4").innerHTML = "Problemas con sus amigos y/o compañeros en la escuela";
                   document.querySelector(".deri5").innerHTML = "La separación o divorcio de tus padres.";
                   document.querySelector(".leer2").innerHTML = "Problemas con sus amigos y/o compañeros en la escuela";
                   document.querySelector(".context10").innerHTML = "Desarrollo personal";
                   document.querySelector(".context11").innerHTML = "Mis problemas comenzaron cuando me transfirieron a un club llamado grande. Siempre había soñado con llegar allí como fanático desde mi infancia. ¿Y quién no querría jugar en un gran club?";
                   document.querySelector(".context12").innerHTML = "Pero sentí presión. Algo que nunca me había afectado en mi club de origen. En los entrenamientos saqué lo mejor de mí y para el entrenador fui el titular clavado para el puesto. Pero no pudo rendir en los partidos, y decayó aún más, en los considerados clave. En resumen, lo que la afición llama: Su camiseta es pesada.";
                   document.querySelector(".context13").innerHTML = "En la cancha me deslumbró. En cada una de mis apariciones, sentí los ojos de miles de aficionados en la nuca, evaluándome, como si fuera, a ejecutar un penal trascendental para un partido final definitorio. En la responsabilidad de resolver cada jugada de forma magistral, como me precedía mi fama, me hacía dudar y no disfrutaba del juego en sí. Hasta que jugar se convirtió en un calvario y me quitó el descanso y el sueño. Llegué al fondo del pozo cuando sufrí una lesión tonta y evitable, que admito que busqué. Pensé que iba a dejar las botas para siempre.";
                   document.querySelector(".context14").innerHTML = "Trabajé con los principios de la metafísica durante algún tiempo y hoy soy querido por la afición y el cuerpo técnico. Yo pago y doy satisfacción tanto a ellos como a mí. Y fundamentalmente, CREO EN MÍ. La presión dejó de pesar sobre mi conciencia. Confío plenamente en mí y disfruto, y me encanta lo que hago, que es jugar en el club de mis amores.";
                   document.querySelector(".context15").innerHTML = "Problemas con sus amigos y/o compañeros en la escuela";
                   document.querySelector(".context16").innerHTML = "La infancia, la describe como perdida en sus propios pensamientos o en las nubes. Una chica tranquila, introvertida y tímida. En la escuela el aprendizaje era difícil para él. Era frustrante no ser aplicada como sus amigas, además su motricidad le generaba mucha frustración por no poder jugar primavera, avión, quemas, volleyball, baloncesto, al igual que sus amigas de la escuela. Se aisló porque no encajaba con grupos de amigos. Esto afectó su autoestima y autoconcepto. A menudo era humillada por sus compañeros y/o profesores por sus dificultades de aprendizaje.";
                   document.querySelector(".context17").innerHTML = "Qué decir en la adolescencia: matemáticas, física y química apenas aprobaron los exámenes. Le costaba tomar decisiones, concentrarse. Quería estudiar una carrera que no tuviera números.";
                   document.querySelector(".context18").innerHTML = "En sus primeros años en la escuela secundaria, le costaba entender las instrucciones para hacer el mejor trabajo posible.";
                   document.querySelector(".context19").innerHTML = "Falta de atención"
                   document.querySelector(".more1").innerHTML = "Leer más sobre...";
                   document.querySelector(".more2").innerHTML = "¿Qué es estrés?";
                   document.querySelector(".leer50").innerHTML = "Leer más";
                   document.querySelector(".leer4").innerHTML = "Leer más";
                   document.querySelector(".leer5").innerHTML = "Leer más";
                   document.querySelector(".more2").innerHTML = "¿Qué es el estrés?";
                   document.querySelector(".more3").innerHTML = "¿Qué es la ansiedad?";
                   document.querySelector(".more4").innerHTML = "¿Qué es depresión?";
                   document.querySelector(".more5").innerHTML = "¿Qué es TDH?";
                   document.querySelector(".more6").innerHTML = "¿Qué es desarrollo personal?";
               // footer
                document.querySelector("#fo1").innerHTML = "Inicio"
                document.querySelector("#fo2").innerHTML = "Sobre nosotros"
                document.querySelector("#fo3").innerHTML = "Psicólogos"
                document.querySelector("#fo4").innerHTML = "Centros de ayuda";
                document.querySelector(".social-text").innerHTML = "¡Nuestras redes sociales!"
                // checkedbutton
                document.querySelector(".trans").appendChild(image).style.width = "50px";
                document.querySelector(".trans").appendChild(img).style.width = "50px";
                document.querySelector(".trans").removeChild(img);
            }
        }
        else if(input){
            if (!input.checked) {
                    localStorage.setItem("idioma", "en")
                   // menu
                   document.querySelector("#link1").innerHTML = "Psychologists";
                   document.querySelector("#link2").innerHTML = "Frequent questions";
                   document.querySelector("#link3").innerHTML = "Testimonials";
                   document.querySelector("#link4").innerHTML = "About us";
                   if (document.querySelector("#Logout")) {
                    document.querySelector("#Logout").innerHTML = "Logout";
                }
                  if (document.querySelector("#Salir")) {
                    document.querySelector("#Salir").innerHTML = "Log In";
                }
                   /*Parte de document querySelector en ingles*/
                   document.querySelector("#first-quote").innerHTML = "The losses generated by mood disorders have an impact on the productivity of a country.";
                   document.querySelector("#second-quote").innerHTML = "The losses generated by these disorders are not only important in social terms, because mental illnesses also have an enormous impact on the productivity of a country.";
                   document.querySelector("#problema1").innerHTML = "Depression";
                   document.querySelector("#testi1").innerHTML = "Testimony of Nicole, freshman";
                   document.querySelector("#context3").innerHTML = "I suffered from depression from the age of 13 to 16, it is something horrible, your whole world is upset every part of your life and how you function in society is affected";
                   document.querySelector(".context2").innerHTML = "The solution was to seek psychological help, take refuge in my family, practice sports, read and play activities, I began to meet and interact with more people because you lock yourself up and the abyss becomes much larger,he explains. Nicole is not the only one who rely on professional assistance to cope with depression.";
                   document.querySelector(".context4").innerHTML = "The other thing is to explain well to family members, they help a lot, without their participation it is fatal";
                   document.querySelector(".context5").innerHTML = "It is that as Carlos, a second year of high school, who has suffered two episodes of severe depression, has had to drop out of the study. And maybe I'll lose the year.";
                   document.querySelector(".context6").innerHTML = "Depression is something that makes us see the world in a very negative way. All the things we do, we do with a very vague feeling that makes us tend to give up the enjoyments of life, says Diego, a former ninth-grade student";
                   document.querySelector(".context7").innerHTML = "They all have symptoms in common.";
                   document.querySelector(".li1").innerHTML = "Feelings of sadness, which may include crying spells for no apparent reason";
                   document.querySelector(".li2").innerHTML = "Frustration or feelings of anger, even over minor matters. (such as failing in a school project).";
                   document.querySelector(".li3").innerHTML = "Feelings of hopelessness or emptiness.";
                   document.querySelector(".li4").innerHTML = "Loss of interest or pleasure in daily activities.";
                   document.querySelector(".leer1").innerHTML = "Read more";
                   document.querySelector(".subtitle_1").innerHTML = "Every day there are more who suffer from anxiety disorders, between 15 and 20% of young people in the country have to deal with this type of disorder. But although it is a topic that is being talked about more and more, it is still not enough. Many are the people who suffer from this and do not seek help for fear of being treated as crazy. If you who are reading us are going through this, do not worry, there are people who can help you.";
                   document.querySelector(".context8").innerHTML = "The testimonies of 7 girls who suffer from anxiety. If you are in the same situation we want to help you open up and if you have someone in your environment who suffers from it, help them in everything you can. Take a look at these testimonials and you will see that you are not alone and that seeking help really works.";
                   document.querySelector(".lipro1").innerHTML = "1. School can be a scary place.";
                   document.querySelector(".pro1").innerHTML = "I suffer from anxiety. From the beginning I've had this problem of not talking to people until I feel comfortable enough with them, and this makes everyone think I'm a self-centered jerk. Sometimes I just try to talk to people and end up making things horribly awkward. School is a scary place because the teachers think I'm shy, and they keep forcing me to speak in front of all my classmates, and that's when I start acting weird and making things even worse. Sara, 16 years old, a first-year high school student."
                   document.querySelector(".lipro2").innerHTML = "2. And hanging out with very stressful friends.";
                   document.querySelector(".pro2").innerHTML = "The thing about social anxiety is that it's a vicious cycle. You want to make friends and socialize, but the stress and fear of being boring or simply having to have a conversation with someone you don't know makes you feel blocked. But missing out and looking at photos and Snapchats from the event the other day only adds to the anxiety, because then you worry about missing out on developing relationships, so the next hangout will be even weirder and more awkward. You want to propose to see them or go to social events, but you are afraid to intervene and be ignored or rejected. And they end up marginalizing you and always leaving you aside because they think that 'you never sign up for anything'. And you feel that people don't really like you and the anxiety ends up winning. Gabriela, 18 years old, third-year high school student.";
                   document.querySelector(".lipro3").innerHTML = "3. Being alone doesn't help either.";
                   document.querySelector(".pro3").innerHTML = "When I started to develop anxiety, I felt excessively self-conscious in public spaces. Thoughts would start running through my head and I would get disoriented if I couldn't calm down. Soon I began to experience panic attacks on a daily basis. My anxiety made me afraid to be with others and sometimes even to be alone, because being alone meant being alone with my thoughts. As I got older, with the help of a therapist, I learned to deal with it. I still have bad days, but now I know how to live with it!” Adriana, 14 years old, ninth grade student";
                   document.querySelector(".lipro4").innerHTML = "4. And that you miss the best moments of life.";
                   document.querySelector(".pro4").innerHTML = "My battle with anxiety affects every aspect of my life and everything I do. I get extremely nervous and uncomfortable around new and old people, constantly finding myself not knowing how to open up to others or even wanting to. Anxiety continually keeps me from participating in activities like school clubs or events, hanging out with friends, spending time with my family, or even going to my Zumba class. Having anxiety keeps me from so many wonderful moments in life that I would love to just live. Angie, 17 years old, a sophomore in high school.";
                   document.querySelector(".lipro5").innerHTML = "5. There should be no prejudice.";
                   document.querySelector(".pro5").innerHTML = "My mother suffers from bipolar disorder, anxiety, depression and alcoholism. When I started Third Cycle I started having panic and anxiety attacks, especially after the elections. Because I was familiar with mental illness, I was able to realize that the anxiety I was suffering from was not terrible and I received the help I needed. I want people to understand that there should be no prejudice for suffering from mental illnesses, so these illnesses could be addressed and treated.” Emiliana, 15 years old, a first-year high school student.";
                   document.querySelector(".lipro6").innerHTML = "6. Therapy and medication can help a lot.";
                   document.querySelector(".pro6").innerHTML = "I developed an anxiety disorder when I was 14 years old. I started having anxiety attacks when I was studying for math tests. I was doing therapy on and off for two years, and recently started taking anxiety medication which has been helping me quite a bit. I was afraid to take medication because I didn't want to be labeled as crazy or people judge me for it. But who cares! My fight is not over yet, but I am much better.” Karla, 15 years old, first year high school student";
                   document.querySelector(".lipro7").innerHTML = "7. You may need to make changes in your life to recover";
                   document.querySelector(".pro7").innerHTML = "Due to my bipolar disorder which led to anxiety, and I have to live a very structured life. I take my medication in the morning with breakfast and I can't skip a day, I hardly drink, and I need 8-10 hours of sleep each night. I used to think that it made me a boring person compared to my previous lifestyle, characterized by great impulsiveness, partying, lack of responsibility with my studies. But looking back I am significantly healthier and happier because of the changes I have made. My friends and family have been great to me regarding my condition, offering me unconditional love and support and I feel extremely lucky for that. What has also helped me a lot in dealing with my illness, along with medication and therapy, is regular exercise; I practice yoga daily and walk everywhere, which has reduced my anxiety in general and has weakened the effects of my bipolarity.” Veronica, 18 years old, third-year high school student.";
                   document.querySelector(".leer2").innerHTML = "Read More...";
                   document.querySelector(".sub2").innerHTML = "Teens, just like adults, can experience stress every day and can benefit from learning stress management skills. Most teens experience more stress when they perceive a situation as dangerous, difficult, or painful and they don't have the resources to deal with it. Some of the sources of stress for teens can include:.";
                   document.querySelector(".deri1").innerHTML = "The demands and frustrations of school";
                   document.querySelector(".deri2").innerHTML = "Negative thoughts and feelings about themselves";
                   document.querySelector(".deri3").innerHTML = "The changes in their bodies";
                   document.querySelector(".deri4").innerHTML = "Problems with their friends and/or peers at school";
                   document.querySelector(".deri5").innerHTML = "The separation or divorce of your parents";
                   document.querySelector(".leer2").innerHTML = "Problems with their friends and/or peers at school";
                   document.querySelector(".context10").innerHTML = "Personal development";
                   document.querySelector(".context11").innerHTML = "My problems started when I was transferred to a so-called big club. I had always dreamed of getting there as a fanatical fan since my childhood. And who wouldn't want to play for a big top club?";
                   document.querySelector(".context12").innerHTML = "But I felt pressure. Something that had never affected me in my home club. In training I brought out the best in me and for the coach I was the starter nailed for the position. But he could not perform in the games, and he declined even more, in those considered key. In short, what the fans call: His shirt is heavy.";
                   document.querySelector(".context13").innerHTML = "On the pitch, he dazzled me. In each of my appearances, I felt the eyes of thousands of fans on the back of my neck evaluating me, as if I were going to take a momentous penalty for a defining final match. In the responsibility of solving each play masterfully, as my fame preceded, it made me doubt and I did not enjoy the game itself. Until playing became an ordeal and took away my rest and sleep. I reached the bottom of the well when I suffered a silly, avoidable injury, which I admit I looked for. I thought I was going to leave the boots forever.";
                   document.querySelector(".context14").innerHTML = "I worked with the principles of metaphysics for some time, and today I am loved by the fans and the coaching staff. I pay and give satisfaction both to them and to me. And fundamentally, I BELIEVE IN ME. The pressure ceased to weigh on my conscience. I fully trust and enjoy myself, and I love what I do, which is to play in the club of my loves.";
                   document.querySelector(".context15").innerHTML = "Problems with their friends and/or peers at school";
                   document.querySelector(".context16").innerHTML = "Childhood, he describes as lost in his own thoughts or in the clouds. A quiet, introverted and shy girl. At school learning was difficult for him. It was frustrating not to be applied like her friends, also her motor skills generated a lot of frustration for not being able to play spring, airplane, burns, bolley, basketball, just like her friends from school. She isolated herself because she didn't fit in with groups of friends. This affected their self-esteem and self-concept. She was often humiliated by her classmates and/or teachers for her learning difficulties";
                   document.querySelector(".context17").innerHTML = "What to say in adolescence: mathematics, physics and chemistry barely passed the exams. It was hard for him to make decisions, to concentrate. I wanted to study a career that had no numbers.";
                   document.querySelector(".context18").innerHTML = "In his first years in high school, he struggled to understand the instructions, to do the best possible job.";
                   document.querySelector(".context19").innerHTML = "Lack of attention"
                   document.querySelector(".more1").innerHTML = "Read More About...";
                   document.querySelector(".more2").innerHTML = "What is stress?";
                   document.querySelector(".leer50").innerHTML = "Read More";
                   document.querySelector(".leer4").innerHTML = "Read More";
                   document.querySelector(".leer5").innerHTML = "Read More";
                   document.querySelector(".more2").innerHTML = "What is stress?";
                   document.querySelector(".more3").innerHTML = "What is anxiety?";
                   document.querySelector(".more4").innerHTML = "What is depression?";
                   document.querySelector(".more5").innerHTML = "What is ADHD?";
                   document.querySelector(".more6").innerHTML = "What Personal development?";
                   /*Parte de document querySelector en ingles*/
                    // footer
                   document.querySelector("#fo1").innerHTML = "Home" 
                   document.querySelector("#fo2").innerHTML = "About us"
                   document.querySelector("#fo3").innerHTML = "Psychologists"
                   document.querySelector("#fo4").innerHTML = "Help centers"
                   document.querySelector(".social-text").innerHTML = "Our social networks!"
                   // checkedbutton
                   document.querySelector(".trans").appendChild(img).style.width = "50px";
                    document.querySelector(".trans").appendChild(image).style.width = "50px";
                    document.querySelector(".trans").removeChild(image);
            }
            else{
                  localStorage.setItem("idioma", "es")
                document.querySelector("#link1").innerHTML = "Psicologos";
                document.querySelector("#link2").innerHTML = "Preguntas frecuentes";
                document.querySelector("#link3").innerHTML = "Testimonios";
                document.querySelector("#link4").innerHTML = "Nuestra identidad";
                if (document.querySelector("#Logout")) {
                    document.querySelector("#Logout").innerHTML = "Salir";
                }
                  if (document.querySelector("#Salir")) {
                    document.querySelector("#Salir").innerHTML = "Entrar";
                }
                   /*Parte de document querySelector en Español*/
                   document.querySelector("#first-quote").innerHTML = "Las pérdidas generadas por los trastornos del estado de ánimo repercuten en la productividad de un país.";
                   document.querySelector("#second-quote").innerHTML = "Las pérdidas que generan estos trastornos no solo son importantes en términos sociales, pues las enfermedades mentales también tienen un enorme impacto en la productividad de un país.";
                   document.querySelector("#problema1").innerHTML = "Depresión";
                   document.querySelector("#testi1").innerHTML = "Testimonio de Nicole, estudiante de primer año";
                   document.querySelector("#context3").innerHTML = "Sufrí de depresión desde los 13 a los 16 años, es algo horrible, todo tu mundo está trastornado cada parte de tu vida y cómo te desenvuelves en la sociedad se ve afectada";
                   document.querySelector(".context2").innerHTML = "La solución fue buscar ayuda psicológica, refugiarme en mi familia, practicar deportes, leer y jugar actividades, comencé a conocer e interactuar con más personas porque uno se encierra y el abismo se hace mucho más grande, explica. Nicole no es la única que confía en la asistencia profesional para hacer frente a la depresión.";
                   document.querySelector(".context4").innerHTML = "Lo otro es explicar bien a los familiares, ayudan mucho, sin su participación es fatal";
                   document.querySelector(".context5").innerHTML = "Es que como Carlos, estudiante de segundo de bachillerato, que ha sufrido dos episodios de depresión severa, ha tenido que abandonar el estudio. Y a lo mejor me pierdo el año.";
                   document.querySelector(".context6").innerHTML = "La depresión es algo que nos hace ver el mundo de una manera muy negativa. Todas las cosas que hacemos, las hacemos con un sentimiento muy vago que nos hace tender a renunciar a los placeres de la vida, dice Diego, exalumno de noveno grado.";
                   document.querySelector(".context7").innerHTML = "Todos ellos tienen síntomas en común.";
                   document.querySelector(".li1").innerHTML = "Sentimientos de tristeza, que pueden incluir accesos de llanto sin razón aparente";
                   document.querySelector(".li2").innerHTML = "Frustración o sentimientos de ira, incluso por asuntos menores. (como fracasar en un proyecto escolar).";
                   document.querySelector(".li3").innerHTML = "Sentimientos de desesperanza o vacío.";
                   document.querySelector(".li4").innerHTML = "Pérdida de interés o placer en las actividades diarias.";
                   document.querySelector(".leer1").innerHTML = "Leer más";
                   document.querySelector(".subtitle_1").innerHTML = "Cada día son más los que padecen trastornos de ansiedad, entre el 15 y el 20% de los jóvenes del país tienen que lidiar con este tipo de trastorno. Pero aunque es un tema del que se habla cada vez más, todavía no es suficiente. Muchas son las personas que sufren de esto y no buscan ayuda por miedo a ser tratados como locos. Si tú que nos estás leyendo estás pasando por esto, no te preocupes, hay personas que te pueden ayudar.";
                   document.querySelector(".context8").innerHTML = "Los testimonios de 7 niñas que sufren de ansiedad. Si estás en la misma situación queremos ayudarte a que te abras y si tienes a alguien de tu entorno que lo padezca, ayúdalo en todo lo que puedas. Echa un vistazo a estos testimonios y verás que no estás solo y que buscar ayuda realmente funciona.";
                   document.querySelector(".lipro1").innerHTML = "1. La escuela puede ser un lugar aterrador.";
                   document.querySelector(".pro1").innerHTML = "Sufro de ansiedad. Desde el principio he tenido este problema de no hablar con la gente hasta que me siento lo suficientemente cómodo con ellos, y esto hace que todos piensen que soy un idiota egocéntrico. A veces solo trato de hablar con la gente y termino haciendo las cosas terriblemente incómodas. La escuela es un lugar aterrador porque los maestros suponen que soy tímido y me siguen obligando a hablar frente a todos mis compañeros de clase, y ahí es cuando empiezo a actuar raro y empeorar las cosas. Sara, 16 años, estudiante de primer año de secundaria."
                   document.querySelector(".lipro2").innerHTML = "2. Y salir con amigas muy estresantes.";
                   document.querySelector(".pro2").innerHTML = "Lo que pasa con la ansiedad social es que es un círculo vicioso. Quieres hacer amigos y socializar, pero el estrés y el miedo a ser aburrido o simplemente tener que tener una conversación con alguien que no conoces te hace sentir bloqueado. Pero perderse y mirar fotos y snapchats del evento del otro día solo aumenta la ansiedad, porque entonces te preocupas por perderte el desarrollo de relaciones, por lo que el próximo lugar de reunión será aún más extraño e incómodo. Quiere proponer, verlos o ir a eventos sociales, pero tiene miedo de intervenir y ser ignorado o rechazado. Y acaban marginándote y dejándote siempre de lado porque piensan que 'nunca te apuntas a nada'. Y sientes que no le caes bien a la gente y te acaba ganando la ansiedad. Gabriela, 18 años, estudiante de tercer año de secundaria.";
                   document.querySelector(".lipro3").innerHTML = "3. Estar solo tampoco ayuda.";
                   document.querySelector(".pro3").innerHTML = "”Cuando comencé a desarrollar ansiedad, me sentía excesivamente cohibido en los espacios públicos. Los pensamientos comenzaban a correr por mi cabeza y me desorientaba si no podía calmarme. Pronto comencé a experimentar ataques de pánico a diario. Mi ansiedad me hizo tener miedo de estar con los demás y, a veces, incluso de estar solo, porque estar solo significaba estar solo con mis pensamientos. A medida que fui creciendo, con la ayuda de un terapeuta, aprendí a lidiar con eso. Todavía tengo días malos, ¡pero ahora sé cómo vivir con eso!”. Adriana, 14 años, estudiante de noveno grado";
                   document.querySelector(".lipro4").innerHTML = "4. Y que te pierdas los mejores momentos de la vida.";
                   document.querySelector(".pro4").innerHTML = "Mi batalla contra la ansiedad afecta todos los aspectos de mi vida y todo lo que hago. Me pongo extremadamente nervioso e incómodo con personas nuevas y viejas, y constantemente me doy cuenta de que no sé cómo abrirme a los demás o ni siquiera quiero hacerlo. La ansiedad continuamente me impide participar en actividades como clubes o eventos escolares, salir con amigos, pasar tiempo con mi familia o incluso ir a mi clase de Zumba. Tener ansiedad me impide vivir tantos momentos maravillosos en la vida que me encantaría vivir. Angie, 17 años, estudiante de segundo año de secundaria.";
                   document.querySelector(".lipro5").innerHTML = "5. No debe haber prejuicios.";
                   document.querySelector(".pro5").innerHTML = "Mi madre sufre de trastorno bipolar, ansiedad, depresión y alcoholismo. Cuando comencé Tercer Ciclo comencé a tener ataques de pánico y ansiedad, sobre todo después de las elecciones. Debido a que estaba familiarizado con la enfermedad mental, pude darme cuenta de que la ansiedad que sufría no era terrible y recibí la ayuda que necesitaba. Quiero que la gente entienda que no debe haber prejuicios por sufrir enfermedades mentales, para que estas enfermedades puedan ser abordadas y tratadas”. Emiliana, 15 años, estudiante de primer año de secundaria.";
                   document.querySelector(".lipro6").innerHTML = "6. La terapia y la medicación pueden ayudar mucho.";
                   document.querySelector(".pro6").innerHTML = "Desarrollé un trastorno de ansiedad cuando tenía 14 años. Empecé a tener ataques de ansiedad cuando estaba estudiando para los exámenes de matemáticas. Estuve haciendo terapia intermitentemente durante dos años, y recientemente comencé a tomar medicamentos para la ansiedad que me han ayudado bastante. Tenía miedo de tomar medicamentos porque no quería que me etiquetaran como loco o que la gente me juzgara por ello. ¡Pero a quién le importa! Mi lucha aún no ha terminado, pero estoy mucho mejor”. Karla, 15 años, estudiante de primer año de secundaria";
                   document.querySelector(".lipro7").innerHTML = "7. Es posible que necesite hacer cambios en su vida para recuperarse";
                   document.querySelector(".pro7").innerHTML = "Debido a mi trastorno bipolar que me llevó a la ansiedad, tengo que vivir una vida muy estructurada. Tomo mi medicamento por la mañana con el desayuno y no puedo saltarme un día, casi no bebo y necesito dormir de 8 a 10 horas cada noche. Solía ​pensar que me convertía en una persona aburrida en comparación con mi estilo de vida anterior, caracterizado por una gran impulsividad, fiesta, falta de responsabilidad con mis estudios. Pero mirando hacia atrás, soy significativamente más saludable y feliz debido a los cambios que he realizado. Mis amigos y mi familia han sido muy buenos conmigo con respecto a mi condición, ofreciéndome amor y apoyo incondicionales y me siento muy afortunada por eso. Lo que también me ha ayudado mucho en el manejo de mi enfermedad, junto con la medicación y la terapia, es el ejercicio regular; practico yoga a diario y camino a todos lados, lo que ha reducido mi ansiedad en general y ha debilitado los efectos de mi bipolaridad”. Verónica, 18 años, estudiante de tercer año de secundaria.";
                   document.querySelector(".leer2").innerHTML = "Leer más...";
                   document.querySelector(".sub2").innerHTML = "Los adolescentes, al igual que los adultos, pueden experimentar estrés todos los días y pueden beneficiarse al aprender habilidades para manejar el estrés. La mayoría de los adolescentes experimentan más estrés cuando perciben una situación como peligrosa, difícil o dolorosa y no tienen los recursos para enfrentarla. Algunas de las fuentes de estrés para los adolescentes pueden incluir:";
                   document.querySelector(".deri1").innerHTML = "Las exigencias y frustraciones de la escuela.";
                   document.querySelector(".deri2").innerHTML = "Pensamientos y sentimientos negativos sobre sí mismos.";
                   document.querySelector(".deri3").innerHTML = "Los cambios en sus cuerpos.";
                   document.querySelector(".deri4").innerHTML = "Problemas con sus amigos y/o compañeros en la escuela";
                   document.querySelector(".deri5").innerHTML = "La separación o divorcio de tus padres.";
                   document.querySelector(".leer2").innerHTML = "Problemas con sus amigos y/o compañeros en la escuela";
                   document.querySelector(".context10").innerHTML = "Desarrollo personal";
                   document.querySelector(".context11").innerHTML = "Mis problemas comenzaron cuando me transfirieron a un club llamado grande. Siempre había soñado con llegar allí como fanático desde mi infancia. ¿Y quién no querría jugar en un gran club?";
                   document.querySelector(".context12").innerHTML = "Pero sentí presión. Algo que nunca me había afectado en mi club de origen. En los entrenamientos saqué lo mejor de mí y para el entrenador fui el titular clavado para el puesto. Pero no pudo rendir en los partidos, y decayó aún más, en los considerados clave. En resumen, lo que la afición llama: Su camiseta es pesada.";
                   document.querySelector(".context13").innerHTML = "En la cancha me deslumbró. En cada una de mis apariciones, sentí los ojos de miles de aficionados en la nuca, evaluándome, como si fuera, a ejecutar un penal trascendental para un partido final definitorio. En la responsabilidad de resolver cada jugada de forma magistral, como me precedía mi fama, me hacía dudar y no disfrutaba del juego en sí. Hasta que jugar se convirtió en un calvario y me quitó el descanso y el sueño. Llegué al fondo del pozo cuando sufrí una lesión tonta y evitable, que admito que busqué. Pensé que iba a dejar las botas para siempre.";
                   document.querySelector(".context14").innerHTML = "Trabajé con los principios de la metafísica durante algún tiempo y hoy soy querido por la afición y el cuerpo técnico. Yo pago y doy satisfacción tanto a ellos como a mí. Y fundamentalmente, CREO EN MÍ. La presión dejó de pesar sobre mi conciencia. Confío plenamente en mí y disfruto, y me encanta lo que hago, que es jugar en el club de mis amores.";
                   document.querySelector(".context15").innerHTML = "Problemas con sus amigos y/o compañeros en la escuela";
                   document.querySelector(".context16").innerHTML = "La infancia, la describe como perdida en sus propios pensamientos o en las nubes. Una chica tranquila, introvertida y tímida. En la escuela el aprendizaje era difícil para él. Era frustrante no ser aplicada como sus amigas, además su motricidad le generaba mucha frustración por no poder jugar primavera, avión, quemas, volleyball, baloncesto, al igual que sus amigas de la escuela. Se aisló porque no encajaba con grupos de amigos. Esto afectó su autoestima y autoconcepto. A menudo era humillada por sus compañeros y/o profesores por sus dificultades de aprendizaje.";
                   document.querySelector(".context17").innerHTML = "Qué decir en la adolescencia: matemáticas, física y química apenas aprobaron los exámenes. Le costaba tomar decisiones, concentrarse. Quería estudiar una carrera que no tuviera números.";
                   document.querySelector(".context18").innerHTML = "En sus primeros años en la escuela secundaria, le costaba entender las instrucciones para hacer el mejor trabajo posible.";
                   document.querySelector(".context19").innerHTML = "Falta de atención"
                   document.querySelector(".more1").innerHTML = "Leer más sobre...";
                   document.querySelector(".more2").innerHTML = "¿Qué es estrés?";
                   document.querySelector(".leer50").innerHTML = "Leer más";
                   document.querySelector(".leer2").innerHTML = "Leer más";
                   document.querySelector(".leer4").innerHTML = "Leer más";
                   document.querySelector(".leer5").innerHTML = "Leer más";
                   document.querySelector(".more2").innerHTML = "¿Qué es el estrés?";
                   document.querySelector(".more3").innerHTML = "¿Qué es la ansiedad?";
                   document.querySelector(".more4").innerHTML = "¿Qué es depresión?";
                   document.querySelector(".more5").innerHTML = "¿Qué es TDH?";
                   document.querySelector(".more6").innerHTML = "¿Qué es desarrollo personal?";
               // footer
                document.querySelector("#fo1").innerHTML = "Inicio"
                document.querySelector("#fo2").innerHTML = "Sobre nosotros"
                document.querySelector("#fo3").innerHTML = "Psicólogos"
                document.querySelector("#fo4").innerHTML = "Centros de ayuda";
                document.querySelector(".social-text").innerHTML = "¡Nuestras redes sociales!"
                // checkedbutton
                document.querySelector(".trans").appendChild(image).style.width = "50px";
                document.querySelector(".trans").appendChild(img).style.width = "50px";
                document.querySelector(".trans").removeChild(img);
            }
        }
    }



    idioma.addEventListener("click", () => {
        let input = document.querySelector("#translate");
        traducir(null, input )
       
    })